### ISSUE TITLE
question: How to deploy server side on Ubuntu

### ISSUE THREAD

**Issue by jks0212** [mpromonet/webrtc-streamer#119]
I have succeeded in implementing client side with my IP Camera. It works pretty well. But Server side, I am using demo server which address is "https://rtsp2webrtc.herokuapp.com/".
I have tried to deploy this project on my Ubuntu but I am not following installation steps.
"Build WebRTC with H264 support" and "Build WebRTC Streamer" which are posted on this project I quite don't understand. And some commands(fetch, gn gen) are not working properly.
After searching about "Building WebRTC" I found about that commands and installed, but I am not sure that I installed correctly and commands also not working.
It's really confusing to me but I really need this project.
What I want to do is, IP Camera(RTSP protocol) and browser(Chrome) are connected each other(P2P) wihch means it doesn't need any relay server(TURN). Only needs STUN Server.
The reason that I need to implement this structure is without relay server can save huge traffic resources.

**Comment by mpromonet** [comment]
Hi jks0212,

In order to install it on a ubuntu server (above xenial) the simplest way is to download the latest [release](https://github.com/mpromonet/webrtc-streamer/releases/download/v0.0.10/webrtc-streamer_v0.0.10_x86_64.tgz), uncompress it and run webrtc-streamer executable.

If you like to build it you can look to [Dockerfile](https://github.com/mpromonet/webrtc-streamer/blob/master/Dockerfile) or [circleci.yml](https://github.com/mpromonet/webrtc-streamer/blob/master/.circleci/config.yml) that build the project.

Best Regards,
Michel.

**Comment by jks0212** [comment]
It is working. Thanks!
