### ISSUE TITLE
Can webrtc-streamer meet my needs

### ISSUE THREAD

**Issue by bkoblenz** [mpromonet/webrtc-streamer#166]
I am trying to download and experiment with this software for a particular need.  I have really be struggling with getting things built the last few days and it appears the build procedure recently changed.  So I have a few comments/suggestions:
1) Both the old and the new build procedure rely on depot-tools/fetch for webrtc.  I am using fetch --no-history webrtc on a t2.micro instance in AWS and it generally does not complete.  I have tried wiping the source and retrying without success.    My first problem was that 8GB of root partition was not enough.  Now, I am typically stuck at:
Syncing projects:  34% (11/32) src/tools/swarming_client
This happened both with the clean download, and with the gclient sync restart.  Any advice?
2) I tried to run cmake but the CMakeLists.txt file actually was never downloaded so that failed too.  Is it possible that fetch would not download all necessary files?

Also, I think the documentation states fetch webrtc --no-history and it should be fetch --no-history webrtc.  It seems that fetch is sensitive to parameter ordering.

But what I really want to know (assuming I can get past these build problems) is webrtc-streamer a good fit for my needs and how might I best organize the various pieces.    My use case looks like:

   Subnet                                  Cloud                                                            Subnet 
   -----------|                 S(erver) (https) running on AWS                       |--------------
B(rowser)    |    -------   with both public and private            -----------|  D(evice) ---|---- C(amera)
   -----------|                  IP addresses                                                     |-----------    |----C2(amera)

D and C and C2 are on the same subnet and there is a tunnel from S to D so S and D can directly talk to each other.
I am running live555ProxyServer on D so, in theory, S can directly reference C and C2 by referring to rtsp://D:8554/proxyStream-{1,2}

Since I already have all my protection implemented in my https server on S, it seems having the /api calls go to my server seems appropriate, but I am not sure how to get my server to make the appropriate calls  to actually implement the streaming.  Am I thinking about this the wrong way?

Also, I expect to have multiple users accessing S and each user is only entitled to see the cameras they own.

thanks for any insight.  If there is a better forum for this kind of question please let me know.
-brian

**Comment by mpromonet** [comment]
Hi Brian,

Thanks for reporting the error in fetch command.

About the build, if the fetch is stopping, it may be because the m2.micro has not enough memory.
I do not understand why CMakeLists.txt is missing, it is a part of the repo, maybe cmake is run from the wrong folder.

Still now there is no user management, any user can access to all the streams that are declared in the command line or in the config.json file. Moreover any user can access to any rtsp stream the webrtc-streamer could reach. If you have a rtsp stream H264 available from internet you should be able to reach it using https://rtsp2webrtc.herokuapp.com/webrtcstreamer.html?<rtspurl>

Best Regards,
Michel.
