### ISSUE TITLE
It is possibile? share raspicam with android app?

### ISSUE THREAD

**Issue by blademckain** [mpromonet/webrtc-streamer#229]
would it be possible with this docker, share the raspicam with an android application?
Are there any Android applications that already support WebRTC?

**Comment by mpromonet** [comment]
Hi blademckain,
with the docker or with the application on a raspberry you can stream the raspicam over webrtc.
In order to use it in android application, you could use chrome, or an electron application, or write an app that connect the webrts stream.
Some time ago, I made some tries using the jitsi application, there is some works to do... jitsi communication need time to be understood...
Best Regards,
Michel.

**Comment by blademckain** [comment]
thx
