### ISSUE TITLE
Non local access issues

### ISSUE THREAD

**Issue by Garyguosha** [mpromonet/webrtc-streamer#407]
Hey mpromonet,

I use docker to run webrtc_ Streamer, can display video monitoring in local access, but only the page can be displayed when other computers access, and the video monitoring screen fails to display.Please give me some advice.
![Snipaste_2021-04-09_11-34-28](https://user-images.githubusercontent.com/40396637/114124509-36607f00-9927-11eb-89ba-42eebc5dc9b2.png)

**Comment by mpromonet** [comment]
Hi @Garyguosha 

Did you try running docker with `--net=host` ?

I guess the problem is because ICE negociation doesnot have candidate with the docker host, it has probably candidate with internal docker ip (that is not reachable outside docker) and candidate with your public ip, that is also not the docker host one.
A possible way without `--net=host` may be to run a STUN/TURN server on your LAN instead of using th google STUN.

Best Regards,
Michel.

**Comment by Garyguosha** [comment]
ok  thanks
